### ISSUE TITLE
Provide instructions for downloading labelled data

### ISSUE THREAD

**Issue by kareemn** [Tarteel-io/Tarteel-ML#1]
Is the tarteel.io dataset (or a subset of the data) available for download?

**Comment by tifa2UP** [comment]
You made it here @kareemn 👋

The dataset of raw recordings is available on this link: http://tarteel.io/download-audio. 

We haven't made it available on the website yet since we still need to version the dataset and link demographics etc. Closing the issue but feel free to reopen if you're having trouble with it. 

Close
